services:
  - type: web
    name: ifsp-agendamento
    env: java
    plan: free
    region: oregon
    buildCommand: "./mvnw clean package -DskipTests"
    startCommand: "java -jar target/projeto-0.0.1-SNAPSHOT.jar"
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: ifsp_agendamentos_db
          property: connectionString
      - key: DATABASE_USER
        fromDatabase:
          name: ifsp_agendamentos_db
          property: user
      - key: DATABASE_PASSWORD
        fromDatabase:
          name: ifsp_agendamentos_db
          property: password
databases:
  - name: ifsp_agendamentos_db
    plan: free
